export const LOGIN_PAYLOAD = {
  type: 'doctor',
  username: 'username',
  password: 'password',
};

//Expected Get Response
export const LOGIN_RESPONSE = {
  jwt: 'string',
  user: {
    _id: 1,
    name: 'string',
    email: 'string',
    phone: 'string',
    role: 'doctor', //staff,reception/lab/admin
    type: 'string', //only for doctor
    profileImageURL: 'string',
    createdAt: 'string',
    updatedAt: 'string',
  },
};

//Expected Dashboard Response
export const DASHBOARD_RESPONSE = {
  patient: [
    {
      id: 1,
      regDate: '02/02/2024',
      patientName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Registration',
      refer: 'Not Referred',
      visitCount: '8',
      isAdmitted: true,
      isViewed: true,
      consultantType: 'eye',
      consultantName: 'Dr. Abhay Patil',
    },
    {
      id: 2,
      regDate: '03/02/2024',
      patientName: 'Devesh Thakare',
      sex: 'Male',
      age: '21',
      contactNo: '8208030973',
      type: 'Appointment',
      refer: 'Not Referred',
      visitCount: '12',
      isAdmitted: false,
      isViewed: false,
      consultantType: 'eye',
      consultantName: 'Dr. Abhay Patil',
    },
    {
      id: 3,
      regDate: '22/02/2024',
      patientName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Follow Up',
      refer: 'Not Referred',
      visitCount: '3',
      isAdmitted: true,
      isViewed: true,
      consultantType: 'eye',
      consultantName: 'Dr. Abhay Patil',
    },
    {
      id: 4,
      regDate: '23/02/2024',
      patientName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Registration',
      refer: 'Not Referred',
      visitCount: '1',
      isAdmitted: false,
      isViewed: true,
      consultantType: 'eye',
      consultantName: 'Dr. Abhay Patil',
    },
    {
      id: 5,
      regDate: '12/02/2024',
      patientName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Registration',
      refer: 'Referred',
      visitCount: '5',
      isAdmitted: true,
      isViewed: true,
      consultantType: 'eye',
      consultantName: 'Dr. Abhay Patil',
    },
    {
      id: 6,
      regDate: '10/02/2024',
      patientName: 'Lokesh Thakare',
      sex: 'Male',
      age: '26',
      contactNo: '7218509409',
      type: 'Registration',
      refer: 'Referred',
      visitCount: '2',
      isAdmitted: true,
      isViewed: true,
      consultantType: 'eye',
      consultantName: 'Dr. Abhay Patil',
    },
  ],
};

export const PATIENT_REGISTRATION_PAYLOAD = {
  oldPatient: 'no',
  name: 'Lokesh Thakare',
  address: 'Bhumi Aditi Galaxy,Flat no - 404',
  taluka: 'Aurangabad',
  district: 'Aurangabad',
  dob: '2016-01-16',
  age: 26,
  sex: 'Male',
  mobile: '7218509409',
  consultant: 'Dr. Eknath Pawar',
  visitType: 'Eye Checkup',
  weight: 92,
  pulse: 72,
  bp: 120,
  temperature: 98,
  referredBy: 'No one',
  complaints: 'Headache,Backpain',
  patientLivePic:"url", //TBD
  imageUploaded: "url", //TBD
  searchQuery: '',
  barcode:''
};
