name: Smart Deploy to Hosting

on:
  push:
    branches:
      - test
  pull_request:
    types: [closed]
    branches:
      - master

env:
  FRONTEND_DIR: frontend
  BACKEND_DIR: backend
  SSH_PORT: 22

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      frontend-changed: ${{ steps.check-changes.outputs.frontend }}
      backend-changed: ${{ steps.check-changes.outputs.backend }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect Changes
        id: check-changes
        run: |
          # Debug information
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_BASE_REF: ${{ github.base_ref }}"
          
          # For push events to test branch, compare with previous commit
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/test" ]]; then
            echo "::group::Push to test branch changes"
            echo "Comparing HEAD~1 with HEAD for push event"
            git log -2 --oneline
            frontend_changes=$(git diff --name-only HEAD~1 HEAD -- "$FRONTEND_DIR/" | wc -l)
            backend_changes=$(git diff --name-only HEAD~1 HEAD -- "$BACKEND_DIR/" | wc -l)
            echo "::endgroup::"
          # For push to master or PR closed events
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/master" ]] || 
               [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "::group::Master branch update changes"
            merge_commit="${{ github.event.after || github.sha }}"
            parents=$(git show --no-patch --format="%P" $merge_commit)
            master_parent=$(echo $parents | cut -d' ' -f1)
          
            frontend_changes=$(git diff --name-only $master_parent $merge_commit -- "$FRONTEND_DIR/" | wc -l)
            backend_changes=$(git diff --name-only $master_parent $merge_commit -- "$BACKEND_DIR/" | wc -l)
            echo "::endgroup::"
          fi
          
          echo "frontend=$([ $frontend_changes -gt 0 ] && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "backend=$([ $backend_changes -gt 0 ] && echo true || echo false)" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy If Needed
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-changed == 'true' || needs.detect-changes.outputs.backend-changed == 'true'
    runs-on: ubuntu-latest
    env:
      FRONTEND_DEPLOY_PATH: ${{ github.ref == 'refs/heads/master' && 'domains/webiflysolutions.com/public_html/new_hms' || 'domains/webiflysolutions.com/public_html/new_hms/new_hms_test' }}
      BACKEND_DEPLOY_PATH: ${{ github.ref == 'refs/heads/master' && 'domains/webiflysolutions.com/public_html/new_hms/backend' || 'domains/webiflysolutions.com/public_html/new_hms/new_hms_test/backend' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Required Secrets
        run: |
          if [[ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]]; then
            echo "::error::Missing SSH_PRIVATE_KEY secret"
            exit 1
          fi
          if [[ -z "${{ secrets.SSH_USERNAME }}" ]]; then
            echo "::error::Missing SSH_USERNAME secret"
            exit 1
          fi
          if [[ -z "${{ secrets.SSH_HOST }}" ]]; then
            echo "::error::Missing SSH_HOST secret"
            exit 1
          fi

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT || env.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Node.js
        if: needs.detect-changes.outputs.frontend-changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ${{ env.FRONTEND_DIR }}/package-lock.json

      - name: Build Frontend
        if: needs.detect-changes.outputs.frontend-changed == 'true'
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          npm ci
          npm run build:prod

      - name: Setup PHP
        if: needs.detect-changes.outputs.backend-changed == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Install PHP Dependencies
        if: needs.detect-changes.outputs.backend-changed == 'true'
        working-directory: ${{ env.BACKEND_DIR }}
        run: composer install --no-dev --optimize-autoloader

      - name: Ensure Deployment Paths Exist
        run: |
          if [[ "${{ needs.detect-changes.outputs.frontend-changed }}" == 'true' ]]; then
            ssh -p ${{ secrets.SSH_PORT || env.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              "mkdir -p $FRONTEND_DEPLOY_PATH"
          fi
          if [[ "${{ needs.detect-changes.outputs.backend-changed }}" == 'true' ]]; then
            ssh -p ${{ secrets.SSH_PORT || env.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              "mkdir -p $BACKEND_DEPLOY_PATH"
          fi

      - name: Deploy Frontend
        if: needs.detect-changes.outputs.frontend-changed == 'true'
        run: |
          rsync -avz --delete-excluded --progress -e "ssh -p ${{ secrets.SSH_PORT || env.SSH_PORT }}" \
            --exclude='.env*' \
            --exclude='new_hms_test/' \
          --exclude='backend/' \
            ${{ env.FRONTEND_DIR }}/dist/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:$FRONTEND_DEPLOY_PATH

      - name: Deploy Backend
        if: needs.detect-changes.outputs.backend-changed == 'true'
        run: |
          rsync -avz --delete-excluded --progress -e "ssh -p ${{ secrets.SSH_PORT || env.SSH_PORT }}" \
            --exclude='.env*' \
            --exclude='storage/' \
            --exclude='tests/' \
            ${{ env.BACKEND_DIR }}/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:$BACKEND_DEPLOY_PATH

      - name: Run Migrations
        if: needs.detect-changes.outputs.backend-changed == 'true'
        run: |
          ssh -p ${{ secrets.SSH_PORT || env.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "cd $BACKEND_DEPLOY_PATH && php artisan migrate --seed --force"

      - name: Deployment Complete
        run: echo "::notice::🎉 Deployment completed successfully"