name: Smart Deploy to Hosting

on:
  push:
    branches:
      - test
  pull_request:
    types: [closed]
    branches:
      - master

env:
  FRONTEND_DIR: frontend
  BACKEND_DIR: backend
  SSH_PORT: 22  # Default port if not specified in secrets

jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    outputs:
      frontend-changed: ${{ steps.check-changes.outputs.frontend }}
      backend-changed: ${{ steps.check-changes.outputs.backend }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for proper diff

      - name: Detect Changes
        id: check-changes
        run: |
          # For push events, compare with previous commit
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Comparing HEAD~1 with HEAD for push event"
            frontend_changes=$(git diff --name-only HEAD~1 HEAD | grep -c "^$FRONTEND_DIR/")
            backend_changes=$(git diff --name-only HEAD~1 HEAD | grep -c "^$BACKEND_DIR/")
          else
            # For PR events, compare with base ref
            echo "Comparing ${{ github.event.pull_request.base.ref }} with HEAD for PR event"
            frontend_changes=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -c "^$FRONTEND_DIR/")
            backend_changes=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -c "^$BACKEND_DIR/")
          fi

          echo "Frontend changes detected: $frontend_changes"
          echo "Backend changes detected: $backend_changes"

          echo "frontend=$( [ $frontend_changes -gt 0 ] && echo true || echo false )" >> $GITHUB_OUTPUT
          echo "backend=$( [ $backend_changes -gt 0 ] && echo true || echo false )" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy If Needed
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-changed == 'true' || needs.detect-changes.outputs.backend-changed == 'true'
    runs-on: ubuntu-latest
    env:
      FRONTEND_DEPLOY_PATH: ${{ github.ref == 'refs/heads/master' && 'domains/webiflysolutions.com/public_html/new_hms' || 'domains/webiflysolutions.com/public_html/new_hms/new_hms_test' }}
      BACKEND_DEPLOY_PATH: ${{ github.ref == 'refs/heads/master' && 'domains/webiflysolutions.com/public_html/new_hms/backend' || 'domains/webiflysolutions.com/public_html/new_hms/new_hms_test/backend' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Required Secrets
        run: |
          if [[ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]]; then
            echo "::error::Missing SSH_PRIVATE_KEY secret"
            exit 1
          fi
          if [[ -z "${{ secrets.SSH_USERNAME }}" ]]; then
            echo "::error::Missing SSH_USERNAME secret"
            exit 1
          fi
          if [[ -z "${{ secrets.SSH_HOST }}" ]]; then
            echo "::error::Missing SSH_HOST secret"
            exit 1
          fi

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT || env.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Setup Node.js
        if: needs.detect-changes.outputs.frontend-changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ${{ env.FRONTEND_DIR }}/package-lock.json

      - name: Build Frontend
        if: needs.detect-changes.outputs.frontend-changed == 'true'
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          npm ci
          npm run build:prod

      - name: Setup PHP
        if: needs.detect-changes.outputs.backend-changed == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer

      - name: Cache Composer Dependencies
        if: needs.detect-changes.outputs.backend-changed == 'true'
        uses: actions/cache@v3
        with:
          path: ${{ env.BACKEND_DIR }}/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles(format('{0}/composer.lock', env.BACKEND_DIR)) }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP Dependencies
        if: needs.detect-changes.outputs.backend-changed == 'true'
        working-directory: ${{ env.BACKEND_DIR }}
        run: composer install --no-dev --optimize-autoloader

      - name: Validate Remote Deployment Paths
        run: |
          if [[ "${{ needs.detect-changes.outputs.frontend-changed }}" == 'true' ]]; then
            ssh -p ${{ secrets.SSH_PORT || env.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              "[ -d $FRONTEND_DEPLOY_PATH ]" || { echo "::error::Frontend path missing"; exit 1; }
          fi
          if [[ "${{ needs.detect-changes.outputs.backend-changed }}" == 'true' ]]; then
            ssh -p ${{ secrets.SSH_PORT || env.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              "[ -d $BACKEND_DEPLOY_PATH ]" || { echo "::error::Backend path missing"; exit 1; }
          fi

      - name: Deploy Frontend
        if: needs.detect-changes.outputs.frontend-changed == 'true'
        run: |
          rsync -avz --delete --progress -e "ssh -p ${{ secrets.SSH_PORT || env.SSH_PORT }}" \
            ${{ env.FRONTEND_DIR }}/dist/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:$FRONTEND_DEPLOY_PATH

      - name: Deploy Backend
        if: needs.detect-changes.outputs.backend-changed == 'true'
        run: |
          rsync -avz --delete --progress -e "ssh -p ${{ secrets.SSH_PORT || env.SSH_PORT }}" \
            --exclude='.env' \
            --exclude='storage/*' \
            --exclude='tests/' \
            ${{ env.BACKEND_DIR }}/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:$BACKEND_DEPLOY_PATH

      - name: Run Migrations
        if: needs.detect-changes.outputs.backend-changed == 'true'
        run: |
          ssh -p ${{ secrets.SSH_PORT || env.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "cd $BACKEND_DEPLOY_PATH && php artisan migrate --seed --force"

      - name: Deployment Complete
        run: echo "::notice::🎉 Deployment completed successfully"